# Generated by Django 3.2.5 on 2021-07-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lenderBorrower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookcondtion', models.IntegerField()),
                ('punctuality', models.IntegerField()),
                ('reasonForFlagging', models.CharField(default='', max_length=20)),
                ('flagTheUser', models.BooleanField()),
                ('countForMishnadling', models.IntegerField()),
                ('countForNoShow', models.IntegerField()),
                ('lenderBorrowerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenderBorrower.lenderborrower')),
            ],
        ),
    ]
