# Generated by Django 3.2.5 on 2021-07-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(default='', max_length=255)),
                ('authorname', models.CharField(default='', max_length=255)),
                ('genre', models.CharField(default='', max_length=50)),
                ('publisher', models.CharField(default='', max_length=100)),
                ('yearofpublishing', models.IntegerField()),
                ('condition', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=255)),
                ('bookphoto', models.CharField(default='', max_length=100)),
                ('bookstatus', models.CharField(default='', max_length=100))
                    
    ])
        ]
