# Generated by Django 3.2.5 on 2021-07-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LenderBorrower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='', max_length=20)),
                ('borrowerStartdate', models.DateTimeField()),
                ('borrowerEnddate', models.DateTimeField()),
                ('lenderEnddate', models.DateTimeField()),
                ('lenderStartdate', models.DateTimeField()),
                ('userType', models.CharField(default='', max_length=20)),
                ('returnPolicy', models.CharField(default='', max_length=2000)),
                ('hasWishlist', models.BooleanField()),
                ('lendingpolicyAgreement', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(default='', max_length=255)),
                ('authorname', models.CharField(default='', max_length=255)),
                ('genre', models.CharField(default='', max_length=50)),
                ('publisher', models.CharField(default='', max_length=100)),
                ('yearofpublishing', models.IntegerField()),
                ('condition', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=255)),
                ('bookphoto', models.CharField(default='', max_length=100)),
                ('bookstatus', models.CharField(default='', max_length=100)),
                ('lenderBorrowerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenderBorrower.lenderborrower')),
            ],
        ),
    ]
