# Generated by Django 3.2.5 on 2021-09-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       
        ('lenderBorrower', '0002_auto_20210723_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lenderBorrowerId',
        ),
        migrations.DeleteModel(
            name='LenderBorrower',
        ),
    ]
