# Generated by Django 3.2.5 on 2021-07-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('userId', models.CharField(default='', max_length=50)),
                ('userPassword', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=255)),
                ('pincode', models.CharField(default='', max_length=50)),
                ('mobileno', models.BigIntegerField(default=0)),
                ('emailid', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
