# Generated by Django 3.2.5 on 2021-07-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='userId',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
