# Generated by Django 3.2.5 on 2021-10-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20210711_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='userId',
            new_name='username',
        ),
    ]
